config/routes.rb
Rails.application.routes.draw do
  resources :snippets

  mount Resque::Server.new, at: '/resque'

  root to: 'snippets#index'
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  enum language: [ :ruby, :python, :javascript ]

  validates :language, presence: true
  validates :plain_code, presence: true

  # http://markup.su/highlighter/api
  API_URI = 'http://markup.su/api/highlighter'
  API_THEME = 'Cobalt'
  API_LANGUAGES = {
    ruby: 'Ruby',
    python: 'Python',
    javascript: 'JavaScript'
  }

  def api_post_data
    {
      language: API_LANGUAGES[language.to_sym],
      theme: API_THEME,
      source: plain_code
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        enqueue_snippet_highlighter

        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        @snippet.update_attribute(:highlighted_code, nil)

        enqueue_snippet_highlighter

        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:language, :plain_code)
    end

    def enqueue_snippet_highlighter
      Resque.enqueue(SnippetHighlighter, @snippet.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def formatted_language snippet
    Snippet::API_LANGUAGES[snippet.language.to_sym]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeSnippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.select :language, Snippet.languages.keys.map { |k| [Snippet::API_LANGUAGES[k.to_sym], k] } %>
  </div>
  <div class="field">
    <%= f.label :plain_code %><br>
    <%= f.text_area :plain_code, rows: 20, cols: 80 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Snippets</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td valign="top"><%= formatted_language snippet %></td>
        <td>
          <% if snippet.highlighted_code.present? %>
            <%= raw snippet.highlighted_code %>
          <% else %>
            <pre><%= snippet.plain_code %></pre>
          <% end %>
        </td>
        <td valign="top"><%= link_to 'Show', snippet %></td>
        <td valign="top"><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td valign="top"><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= formatted_language @snippet %>
</p>

<p>
  <strong>Code:</strong>

  <% if @snippet.highlighted_code.present? %>
    <%= raw @snippet.highlighted_code %>
  <% else %>
    <pre><%= @snippet.plain_code %></pre>
  <% end %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>